### PR TITLE
Implements display for dense matrices

### PR DESCRIPTION
**Pull request by krishnakumarg1984**
- Indexing by `[row,col]` does not yet work
- Unsure of how to print complex numbers
- Matrix width calculation to be fixed

### CODE REVIEW

**Comment by tbetcke** [comment]
- Why do you need indexing for the code? Using `get` is perfectly fine.
- Complex numbers should just print. Have you tested?

**Comment by krishnakumarg1984** [comment]
@tbetcke We need to think how to print complex-number output. I am happy with the printing of any sized real-matrices. Have improved the robustness of the code. Can you please review?

**Comment by tbetcke** [comment]
You can do it for different data types by doing a macro and implementing your format routine explicitly for the different scalar types (f32, f64, c32, c64).

**Comment by krishnakumarg1984** [comment]
@tbetcke We now have ability to print complex-valued matrices thanks to declarative macros.

Pending
- move the pseudo tests to example doctests
- adds `to_stdout()` overload for user-settable print widths

**Comment by tbetcke** [comment]
Closing as was included in pull request #28

**Pull request closed without merging**
